services:
  - type: web
    name: fragrantica-final-web
    env: python
    buildCommand: |
      echo "🚀 Начинаем сборку проекта..."
      echo "📦 Обновляем pip..."
      pip install --upgrade pip
      echo "📦 Устанавливаем greenlet с флагами совместимости..."
      pip install greenlet>=3.0.0 --no-binary=greenlet
      echo "📦 Устанавливаем остальные зависимости..."
      pip install -r requirements.txt
      echo "🌐 Устанавливаем Playwright..."
      playwright install chromium
      echo "📁 Проверяем структуру проекта..."
      ls -la
      echo "📁 Проверяем папку web..."
      ls -la web/
      echo "✅ Сборка завершена!"
    startCommand: python3 web/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GL_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true 