services:
  - type: web
    name: fragrantica-parser
    env: python
    buildCommand: pip install --no-deps -r requirements_render.txt && pip install flask beautifulsoup4 requests deep-translator playwright openai && playwright install chromium
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true 