services:
  - type: web
    name: fragrantica-final-web
    env: python
    buildCommand: pip install --only-binary=greenlet -r requirements.txt && playwright install chromium
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true 