services:
  - type: web
    name: fragrantica-final-web
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python3 web/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GL_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true 